export const companyPillars = [
  {
    title: {
      fr: "Sécurité documentaire",
      en: "Document security",
    },
    icon: "security",
    description: {
      fr: "Protéger les documents sensibles, limiter les falsifications et rendre les justificatifs plus difficiles à détourner.",
      en: "Protect sensitive documents, reduce falsification risks and make official records harder to misuse.",
    },
  },
  {
    title: {
      fr: "Authentification",
      en: "Authentication",
    },
    icon: "authentication",
    description: {
      fr: "Permettre la vérification fiable des documents, des vignettes et des informations issues des processus métiers.",
      en: "Enable reliable verification of documents, stickers and information generated by operational processes.",
    },
  },
  {
    title: {
      fr: "Traçabilité",
      en: "Traceability",
    },
    icon: "traceability",
    description: {
      fr: "Relier les données, les contrôles et les preuves terrain afin d’améliorer la transparence opérationnelle.",
      en: "Connect data, inspections and field evidence to improve operational transparency.",
    },
  },
] as const;

export const companyCommitments = [
  {
    title: {
      fr: "Fiabilité opérationnelle",
      en: "Operational reliability",
    },
    description: {
      fr: "Construire des solutions stables, compréhensibles et adaptées aux réalités des centres, des administrations et des équipes terrain.",
      en: "Build stable, understandable solutions adapted to the realities of inspection centers, administrations and field teams.",
    },
  },
  {
    title: {
      fr: "Confiance numérique",
      en: "Digital trust",
    },
    description: {
      fr: "Aider les organisations à mieux contrôler, vérifier et exploiter les informations sensibles.",
      en: "Help organizations better control, verify and use sensitive information.",
    },
  },
  {
    title: {
      fr: "Accompagnement",
      en: "Guidance",
    },
    description: {
      fr: "Soutenir les utilisateurs, les centres et les partenaires dans l’adoption durable des outils déployés.",
      en: "Support users, centers and partners in the long-term adoption of deployed tools.",
    },
  },
  {
    title: {
      fr: "Amélioration continue",
      en: "Continuous improvement",
    },
    description: {
      fr: "Faire évoluer les solutions selon les besoins métier, les contraintes opérationnelles et les retours du terrain.",
      en: "Evolve the solutions according to business needs, operational constraints and field feedback.",
    },
  },
] as const;

export const companyTimeline = [
  {
    period: {
      fr: "Ancrage au Cameroun",
      en: "Cameroon presence",
    },
    title: {
      fr: "Un acteur local dédié aux enjeux du transport.",
      en: "A local player dedicated to transport challenges.",
    },
    description: {
      fr: "PROOFTAG CATIS intervient au Cameroun sur des sujets liés au contrôle technique, à la sécurité documentaire et à la sécurité routière.",
      en: "PROOFTAG CATIS operates in Cameroon on matters related to vehicle inspection, document security and road safety.",
    },
  },
  {
    period: {
      fr: "Depuis 2019",
      en: "Since 2019",
    },
    title: {
      fr: "Déploiement progressif des activités.",
      en: "Progressive deployment of operations.",
    },
    description: {
      fr: "Les activités se structurent autour de la fourniture de solutions numériques, d’équipements, de services et d’un accompagnement destiné aux centres de contrôle technique.",
      en: "Operations have been structured around digital solutions, equipment, services and support for vehicle inspection centers.",
    },
  },
  {
    period: {
      fr: "Aujourd’hui",
      en: "Today",
    },
    title: {
      fr: "Une plateforme de confiance pour l’écosystème.",
      en: "A trust platform for the ecosystem.",
    },
    description: {
      fr: "L’entreprise relie technologie, traçabilité et vérification afin de renforcer la fiabilité des processus liés au transport.",
      en: "The company connects technology, traceability and verification to strengthen the reliability of transport-related processes.",
    },
  },
] as const;

export const companyTechnologyItems = [
  {
    title: {
      fr: "Partenariat technologique avec Prooftag SAS",
      en: "Technology partnership with Prooftag SAS",
    },
    description: {
      fr: "PROOFTAG CATIS porte au Cameroun un savoir-faire technologique issu de Prooftag SAS, reconnu pour ses solutions d’authentification, de sécurisation et de traçabilité.",
      en: "PROOFTAG CATIS brings to Cameroon technological know-how from Prooftag SAS, known for authentication, security and traceability solutions.",
    },
  },
  {
    title: {
      fr: "Certidocs CT comme socle métier",
      en: "Certidocs CT as an operational backbone",
    },
    description: {
      fr: "Certidocs CT structure la sécurisation des processus de contrôle technique, de la donnée issue des contrôles jusqu’à la vérification documentaire.",
      en: "Certidocs CT structures the security of vehicle inspection processes, from inspection data to document verification.",
    },
  },
  {
    title: {
      fr: "Technologies adaptées au terrain",
      en: "Field-ready technologies",
    },
    description: {
      fr: "Les outils sont pensés pour être utilisés par des opérateurs, des centres, des administrations et des équipes de contrôle dans des conditions opérationnelles réelles.",
      en: "The tools are designed for operators, centers, administrations and control teams working in real operational conditions.",
    },
  },
] as const;

export const companyEcosystemRoles = [
  {
    title: {
      fr: "Ministère des Transports",
      en: "Ministry of Transport",
    },
    icon: "authorities",
    description: {
      fr: "S’inscrire dans un environnement où les données de contrôle technique doivent pouvoir être centralisées, consultées et vérifiées par les acteurs habilités.",
      en: "Operate in an environment where vehicle inspection data must be centralizable, accessible and verifiable by authorized stakeholders.",
    },
  },
  {
    title: {
      fr: "Centres de contrôle technique",
      en: "Vehicle inspection centers",
    },
    icon: "centers",
    description: {
      fr: "Fournir des outils, équipements et services qui facilitent la sécurisation des opérations et la qualité des informations produites.",
      en: "Provide tools, equipment and services that help secure operations and improve the quality of generated information.",
    },
  },
  {
    title: {
      fr: "Prooftag SAS",
      en: "Prooftag SAS",
    },
    icon: "technology",
    description: {
      fr: "Apporter un partenariat technologique autour de l’authentification, de la traçabilité et de la sécurisation documentaire.",
      en: "Bring a technology partnership focused on authentication, traceability and document security.",
    },
  },
  {
    title: {
      fr: "Agents de contrôle autorisés",
      en: "Authorized control agents",
    },
    icon: "authorities",
    description: {
      fr: "Rendre les documents et vignettes plus vérifiables sur le terrain afin d’appuyer les contrôles et la lutte contre la fraude.",
      en: "Make documents and stickers more verifiable in the field to support controls and the fight against fraud.",
    },
  },
  {
    title: {
      fr: "Usagers, professionnels et société civile",
      en: "Users, professionals and civil society",
    },
    icon: "users",
    description: {
      fr: "Renforcer la confiance pour les automobilistes, propriétaires, citoyens, assurances, garages, investisseurs et organisations de la société civile.",
      en: "Strengthen trust for drivers, owners, citizens, insurers, garages, investors and civil society organizations.",
    },
  },
] as const;
